module.exports = {
	env: {
		es6: true,
	},
	parserOptions: {
		ecmaVersion: 6,
		sourceType: 'module',
	},
	plugins: [
		'import',
	],
	rules: {
		'grapes/no-internal-import': 'error',
		'import/default': 'error',
		'import/dynamic-import-chunkname': ['off', {
			importFunctions: [],
			webpackChunknameFormat: '[0-9a-zA-Z-_/.]+',
		}],
		'import/export': 'error',
		'import/exports-last': 'error',
		'import/extensions': ['error', 'ignorePackages', {
			js: 'never',
			jsx: 'never',
			mjs: 'never',
		}],
		'import/first': 'error',
		'import/group-exports': 'error',
		'import/imports-first': 'error',
		'import/max-dependencies': ['error', { max: 15 }],
		'import/named': 'error',
		'import/namespace': 'off',
		'import/newline-after-import': 'error',
		'import/no-absolute-path': 'error',
		'import/no-amd': 'error',
		'import/no-anonymous-default-export': 'error',
		'import/no-commonjs': 'off',
		'import/no-cycle': ['error', { maxDepth: Infinity }],
		'import/no-default-export': 'off',
		'import/no-deprecated': 'error',
		'import/no-duplicates': 'error',
		'import/no-dynamic-require': 'error',
		'import/no-extraneous-dependencies': 'off',
		'import/no-internal-modules': ['off', {
			allow: [],
		}],
		'import/no-mutable-exports': 'error',
		'import/no-named-as-default': 'error',
		'import/no-named-as-default-member': 'error',
		'import/no-named-default': 'error',
		'import/no-named-export': 'off',
		'import/no-namespace': 'error',
		'import/no-nodejs-modules': 'off',
		'import/no-relative-parent-imports': 'off',
		'import/no-restricted-paths': 'off',
		'import/no-self-import': 'error',
		'import/no-unassigned-import': ['error', { allow: ['**/*.css', '**/*.scss'] }],
		'import/no-unresolved': ['error', { caseSensitive: true, commonjs: true }],
		'import/no-unused-modules': ['off', {
			ignoreExports: [],
			missingExports: true,
			unusedExports: true,
		}],
		'import/no-useless-path-segments': 'error',
		'import/no-webpack-loader-syntax': 'error',
		'import/order': ['error', { groups: [['builtin', 'external', 'internal']] }],
		'import/prefer-default-export': 'error',
		'import/unambiguous': 'off',
	},
	settings: {
		'import/core-modules': [],
		'import/extensions': [
			'.mjs',
			'.jsx',
		],
		'import/ignore': [
			'node_modules',
			'\\.(coffee|scss|css|less|hbs|svg|json)$',
		],
		'import/resolver': {
			node: {
				extensions: ['.js', '.json'],
			},
		},
	},
};

